name: Test Train
on:
  push:
  pull_request:
    paths:
      - .github/workflows/test_train.yml
      - train/**

defaults:
  run:
    shell: bash
    working-directory: train

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Install uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5.4.2
        with:
          enable-cache: true

      - name: Run lint
        run: |
          uv run ruff check
          uv run ruff format --diff

      - name: Run test train
        run: |
          uv run src/train.py ./config/dummy.yml
