name: Test Infer
on:
  push:
  pull_request:
    paths:
      - .github/workflows/test_infer.yml
      - infer/**

defaults:
  run:
    shell: bash
    working-directory: infer

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Install uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5.4.2

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        with:
          workspaces: "infer"

      - name: Run Rust lint
        run: |
          rustup component add clippy rustfmt  # TODO: dtolnay/rust-toolchainを使う
          cargo clippy --all-targets --all-features -- -D warnings
          cargo fmt --all -- --check

      - name: Run Rust tests
        run: cargo test

      - name: Run Python lint
        working-directory: infer/crates/kanalizer-py
        run: |
          uv run ruff check
          uv run ruff format --diff

      - name: Run Python lint for tools
        working-directory: infer/tools
        run: |
          uv run ruff check
          uv run ruff format --diff
          uv run pyright

      - name: Run Python tests
        working-directory: infer/crates/kanalizer-py
        run: |
          uv run maturin develop
          uv run pytest
